package io.peekandpoke.klang.sprudel.ksp

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import com.google.devtools.ksp.validate

/**
 * KSP processor that generates documentation entries from @SprudelDsl annotated functions and properties.
 *
 * This processor:
 * 1. Finds all functions and properties annotated with @SprudelDsl
 * 2. Extracts KDoc documentation from those symbols
 * 3. Generates FunctionDoc entries automatically
 */
class SprudelDocsProcessor(
    environment: SymbolProcessorEnvironment,
) : SymbolProcessor {

    private val codeGenerator: CodeGenerator = environment.codeGenerator
    private val logger: KSPLogger = environment.logger

    override fun process(resolver: Resolver): List<KSAnnotated> {
        logger.info("SprudelDocsProcessor: Starting documentation generation")

        val annotated = resolver.getSymbolsWithAnnotation("io.peekandpoke.klang.sprudel.lang.SprudelDsl")

        val sprudelDslFunctions = annotated.filterIsInstance<KSFunctionDeclaration>().toList()
        val sprudelDslProperties = annotated.filterIsInstance<KSPropertyDeclaration>().toList()

        logger.info("SprudelDocsProcessor: Found ${sprudelDslFunctions.size} @SprudelDsl functions")
        logger.info("SprudelDocsProcessor: Found ${sprudelDslProperties.size} @SprudelDsl properties")

        if (sprudelDslFunctions.isEmpty() && sprudelDslProperties.isEmpty()) {
            return emptyList()
        }

        generateDocsFile(sprudelDslFunctions, sprudelDslProperties)

        val unprocessed = mutableListOf<KSAnnotated>()
        unprocessed.addAll(sprudelDslFunctions.filterNot { it.validate() })
        unprocessed.addAll(sprudelDslProperties.filterNot { it.validate() })
        return unprocessed
    }

    private fun generateDocsFile(
        functions: List<KSFunctionDeclaration>,
        properties: List<KSPropertyDeclaration>,
    ) {
        // Collect all source files that contain @SprudelDsl symbols so KSP's incremental
        // cache knows to regenerate this file whenever any of them changes.
        val sourceFiles = (functions.mapNotNull { it.containingFile } +
                properties.mapNotNull { it.containingFile }).distinct()

        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = true, *sourceFiles.toTypedArray()),
            packageName = "io.peekandpoke.klang.sprudel.lang.docs",
            fileName = "GeneratedSprudelDocs",
            extensionName = "kt"
        )

        file.bufferedWriter().use { writer ->
            writer.write(generateDocsCode(functions, properties))
        }

        logger.info("SprudelDocsProcessor: Generated documentation file")
    }

    private fun generateDocsCode(
        functions: List<KSFunctionDeclaration>,
        properties: List<KSPropertyDeclaration>,
    ): String {
        // Group by name to handle overloads and property+function pairs
        val functionsByName = functions.groupBy { it.simpleName.asString() }
        val propertiesByName = properties.groupBy { it.simpleName.asString() }
        val allNames = (functionsByName.keys + propertiesByName.keys).distinct().sorted()

        // Split into chunks to avoid JVM MethodTooLargeException (64 KB limit per method).
        // Each chunk becomes a separate private function so no single <clinit> or function
        // exceeds the JVM bytecode size limit.
        val chunks = allNames.chunked(8)

        return buildString {
            appendLine("// Generated by SprudelDocsProcessor - DO NOT EDIT")
            appendLine()
            appendLine("package io.peekandpoke.klang.sprudel.lang.docs")
            appendLine()
            appendLine("import io.peekandpoke.klang.script.types.*")
            appendLine()
            appendLine("/**")
            appendLine(" * Auto-generated Sprudel DSL function documentation.")
            appendLine(" * Generated from @SprudelDsl annotated functions and properties.")
            appendLine(" * Platform-specific actual implementation of the expected declaration.")
            appendLine(" */")

            // One private function per chunk — each stays well within the 64 KB method limit.
            chunks.forEachIndexed { chunkIdx, chunk ->
                appendLine("private fun generatedDocsChunk$chunkIdx() = mapOf(")
                chunk.forEachIndexed { entryIdx, name ->
                    val overloads = functionsByName[name] ?: emptyList()
                    val props = propertiesByName[name] ?: emptyList()
                    append(generateDocEntry(name, overloads, props))
                    if (entryIdx < chunk.size - 1) {
                        appendLine(",")
                    }
                }
                appendLine()
                appendLine(")")
                appendLine()
            }

            // The actual val just combines all chunk maps — keeps <clinit> tiny.
            appendLine("actual val generatedSprudelKlangSymbols: Map<String, KlangSymbol> = buildMap {")
            chunks.forEachIndexed { chunkIdx, _ ->
                appendLine("    putAll(generatedDocsChunk$chunkIdx())")
            }
            appendLine("}")
        }
    }

    private fun generateDocEntry(
        functionName: String,
        overloads: List<KSFunctionDeclaration>,
        properties: List<KSPropertyDeclaration>,
    ): String {
        logger.info(
            "SprudelDocsProcessor: Processing '$functionName' — " +
                    "${overloads.size} function(s), ${properties.size} property(-ies)"
        )

        val parsedFunctionKDocs = overloads.map { function ->
            val kdoc = function.docString
            if (kdoc != null) {
                logger.info("SprudelDocsProcessor: KDoc found for function '$functionName'")
            } else {
                logger.warn("SprudelDocsProcessor: No KDoc found for function '$functionName'")
            }
            KDocParser.parse(kdoc)
        }

        val parsedPropertyKDocs = properties.map { property ->
            val kdoc = property.docString
            if (kdoc == null) {
                logger.warn("SprudelDocsProcessor: No KDoc found for property '$functionName'")
            }
            KDocParser.parse(kdoc)
        }

        val allParsedKDocs = parsedFunctionKDocs + parsedPropertyKDocs

        // Merge category, tags and aliases from all overloads and properties (prefer non-empty)
        val category = allParsedKDocs.mapNotNull { it.category }.firstOrNull() ?: "uncategorized"
        val allTags = allParsedKDocs.flatMap { it.tags }.distinct()
        val allAliases = allParsedKDocs.flatMap { it.aliases }.distinct()

        val tagsString = if (allTags.isNotEmpty()) {
            allTags.joinToString(", ") { "\"$it\"" }
        } else {
            ""
        }

        val aliasesString = if (allAliases.isNotEmpty()) {
            allAliases.joinToString(", ") { "\"$it\"" }
        } else {
            ""
        }

        // Functions first, then properties (properties are the raw/unscaled form)
        val variants = buildList {
            overloads.zip(parsedFunctionKDocs).forEach { (fn, kdoc) ->
                add(generateVariantDoc(fn, kdoc))
            }
            properties.zip(parsedPropertyKDocs).forEach { (prop, kdoc) ->
                add(generatePropertyVariantDoc(prop, kdoc))
            }
        }

        return buildString {
            appendLine()
            appendLine("    \"$functionName\" to KlangSymbol(")
            appendLine("        name = \"$functionName\",")
            appendLine("        category = \"$category\",")
            appendLine("        tags = listOf($tagsString),")
            appendLine("        aliases = listOf($aliasesString),")
            appendLine("        library = \"sprudel\",")
            appendLine("        variants = listOf(")
            variants.forEachIndexed { index, variant ->
                append(variant)
                if (index < variants.size - 1) {
                    appendLine(",")
                }
            }
            appendLine()
            appendLine("        )")
            append("    )")
        }
    }

    private fun generateVariantDoc(function: KSFunctionDeclaration, kdoc: ParsedKDoc): String {
        val functionName = function.simpleName.asString()
        val isExtension = function.extensionReceiver != null
        val receiverType = function.extensionReceiver?.resolve()
        val returnType = function.returnType?.resolve()

        val description = kdoc.description.escapeForRawString()
        val returnDoc = kdoc.returnDoc.replace("\n", " ").escapeForRawString()

        val samplesString = if (kdoc.samples.isNotEmpty()) {
            kdoc.samples.joinToString(",\n") { sample ->
                "                KlangCodeSample(code = \"\"\"${sample.code.escapeForRawString()}\"\"\", type = KlangCodeSampleType.${sample.type.name})"
            }
        } else {
            ""
        }

        return buildString {
            appendLine("            KlangCallable(")
            appendLine("                name = \"$functionName\",")
            if (isExtension && receiverType != null) {
                appendLine("                receiver = ${generateTypeModelCode(receiverType)},")
            }
            val params = function.parameters
            if (params.isNotEmpty()) {
                appendLine("                params = listOf(")
                params.forEach { param ->
                    val paramName = param.name?.asString() ?: return@forEach
                    val paramType = param.type.resolve()
                    val paramDesc = (kdoc.params[paramName] ?: "").replace("\n", " ").escapeForRawString()
                    val paramUiTools = kdoc.paramTools[paramName] ?: emptyList()
                    append("                    KlangParam(")
                    append("name = \"$paramName\", ")
                    append("type = ${generateTypeModelCode(paramType)}")
                    if (param.isVararg) append(", isVararg = true")
                    if (paramDesc.isNotEmpty()) append(", description = \"\"\"$paramDesc\"\"\"")
                    if (paramUiTools.isNotEmpty()) {
                        append(", uitools = listOf(${paramUiTools.joinToString(", ") { "\"$it\"" }})")
                    }
                    val paramSubFields = kdoc.paramSubs[paramName]
                    if (paramSubFields != null && paramSubFields.isNotEmpty()) {
                        append(", subFields = mapOf(${paramSubFields.entries.joinToString(", ") { "\"${it.key}\" to \"\"\"${it.value.escapeForRawString()}\"\"\"" }})")
                    }
                    appendLine("),")
                }
                appendLine("                ),")
            } else {
                appendLine("                params = emptyList(),")
            }
            if (returnType != null) {
                appendLine("                returnType = ${generateTypeModelCode(returnType)},")
            }
            appendLine("                description = \"\"\"$description\"\"\",")
            appendLine("                returnDoc = \"\"\"$returnDoc\"\"\",")

            if (kdoc.samples.isNotEmpty()) {
                appendLine("                samples = listOf(")
                append(samplesString)
                appendLine()
                appendLine("                )")
            } else {
                appendLine("                samples = emptyList()")
            }
            append("            )")
        }
    }

    /** Generates `KlangType(...)` code for a resolved KSP type. */
    private fun generateTypeModelCode(type: KSType): String {
        val declaration = type.declaration
        val simpleName = declaration.simpleName.asString()
        val isTypeAlias = declaration is KSTypeAlias
        val isNullable = type.nullability == Nullability.NULLABLE

        return buildString {
            append("KlangType(simpleName = \"$simpleName\"")
            if (isTypeAlias) append(", isTypeAlias = true")
            if (isNullable) append(", isNullable = true")
            append(")")
        }
    }

    private fun generatePropertyVariantDoc(property: KSPropertyDeclaration, kdoc: ParsedKDoc): String {
        val propertyName = property.simpleName.asString()
        val propertyType = property.type.resolve()
        val propertyTypeSimpleName = propertyType.declaration.simpleName.asString()
        val isExtension = property.extensionReceiver != null
        val receiverType = if (isExtension) property.extensionReceiver!!.resolve() else null

        // DslFunction / DslPatternMethod are callable delegates — not plain objects
        val isDslCallable = propertyTypeSimpleName in setOf("DslFunction", "DslPatternMethod")

        val description = kdoc.description.escapeForRawString()

        val samplesString = if (kdoc.samples.isNotEmpty()) {
            kdoc.samples.joinToString(",\n") { sample ->
                "                KlangCodeSample(code = \"\"\"${sample.code.escapeForRawString()}\"\"\", type = KlangCodeSampleType.${sample.type.name})"
            }
        } else {
            ""
        }

        return buildString {
            if (!isDslCallable && !isExtension) {
                // Plain object / constant
                appendLine("            KlangProperty(")
                appendLine("                name = \"$propertyName\",")
                appendLine("                type = ${generateTypeModelCode(propertyType)},")
                appendLine("                description = \"\"\"$description\"\"\",")
            } else {
                // Callable delegate or extension — emit KlangCallable
                appendLine("            KlangCallable(")
                appendLine("                name = \"$propertyName\",")
                if (receiverType != null) {
                    appendLine("                receiver = ${generateTypeModelCode(receiverType)},")
                }
                // Callable delegate: empty params (no param info available from property)
                appendLine("                params = emptyList(),")
                appendLine("                returnType = KlangType(simpleName = \"SprudelPattern\"),")
                appendLine("                description = \"\"\"$description\"\"\",")
                appendLine("                returnDoc = \"\",")
            }
            if (kdoc.samples.isNotEmpty()) {
                appendLine("                samples = listOf(")
                append(samplesString)
                appendLine()
                appendLine("                )")
            } else {
                appendLine("                samples = emptyList()")
            }
            append("            )")
        }
    }

    /** Escapes content for safe embedding in Kotlin raw strings ("""..."""). */
    private fun String.escapeForRawString(): String {
        return this
            .replace("\$", "\${'$'}")
            .replace("\"\"\"", "\${'\"'}\${'\"'}\${'\"'}")
    }
}
