package io.peekandpoke.klang.strudel.lang.docs

import io.peekandpoke.klang.script.docs.KlangDocsRegistry
import io.peekandpoke.klang.script.types.KlangSymbol

/**
 * Platform-specific generated documentation from @StrudelDsl annotated functions.
 * Actual implementations are generated by KSP in platform-specific source sets.
 */
@Suppress("KotlinNoActualForExpect", "RedundantSuppression")
expect val generatedStrudelKlangSymbols: Map<String, KlangSymbol>

/**
 * Registers all Strudel DSL function documentation with the KlangScript documentation registry.
 *
 * This should be called during initialization to make Strudel documentation available
 * for IDE completion, CodeMirror autocomplete, and documentation pages.
 *
 * @param registry The registry to register docs into (defaults to global registry)
 */
fun registerStrudelDocs(registry: KlangDocsRegistry = KlangDocsRegistry.global) {
    // Register auto-generated docs (all @StrudelDsl functions)
    registry.registerAll(generatedStrudelKlangSymbols)
}
