package io.peekandpoke.klang.audio_bridge.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.symbol.Modifier
import com.google.devtools.ksp.validate

/**
 * Generates the "trust the input" JS-object wire codec for `@WireFormat`-annotated roots and their transitive
 * graph (see `docs/tasks/worklet-codec-ksp.md`). Both worklet ends call the generated `encode_X`/`decode_X`,
 * so the decode just reads properties and constructs — no kotlinx decode driver.
 *
 * Supported shapes: plain scalars (String/Double/Int/Boolean/Float), `DoubleArray` (pass-through), enums
 * (as ordinal Int), nested classes with a primary constructor, sealed classes — including intermediate sealed
 * levels, flattened to leaves — (int `t` type-tag), `data object` sealed subtypes, `List<T>`, `Map<String,Double>`,
 * and nullability of any of those.
 *
 * Anything else (e.g. other typed arrays, `Map` with non-String/Double, a type with no primary constructor) is an
 * ERROR: the processor reports it via `logger.error` (failing the build) with the exact field/subtype path. It never
 * silently skips a type — that would drop data from the wire protocol. To add a wire type, extend the emitter here.
 */
class WireCodecProcessor(
    environment: SymbolProcessorEnvironment,
) : SymbolProcessor {

    private val codeGenerator: CodeGenerator = environment.codeGenerator
    private val logger: KSPLogger = environment.logger

    private var lamCounter = 0
    private fun fresh(): String = "w${lamCounter++}"

    /** Unsupported-shape diagnostics gathered during the walk; reported as build errors (no silent skipping). */
    private val errors = mutableListOf<String>()

    companion object {
        private const val ANN_WIRE_FORMAT = "io.peekandpoke.klang.audio_bridge.WireFormat"
        private const val GEN_PKG = "io.peekandpoke.klang.audio_bridge.wire"

        private const val LIST = "kotlin.collections.List"
        private const val MAP = "kotlin.collections.Map"

        private val SCALARS = setOf(
            "kotlin.String", "kotlin.Double", "kotlin.Int", "kotlin.Boolean", "kotlin.Float", "kotlin.Long",
        )
    }

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val roots = resolver.getSymbolsWithAnnotation(ANN_WIRE_FORMAT)
            .filterIsInstance<KSClassDeclaration>()
            .filter { it.validate() }
            .toList()
        if (roots.isEmpty()) return emptyList()

        // Walk every @WireFormat root's transitive graph. Unsupported shapes are NOT silently skipped — each is
        // recorded with context and reported via logger.error (which fails the build). The codec must cover a
        // type completely or the build breaks, so we never silently drop a field/type from the wire protocol.
        val toGenerate = LinkedHashSet<KSClassDeclaration>()
        errors.clear()
        for (root in roots) {
            collectType(root.asStarProjectedType(), toGenerate, root.simpleName.asString())
        }

        if (errors.isNotEmpty()) {
            errors.distinct().forEach { logger.error("[wire-codec] $it") }
            return emptyList()
        }
        if (toGenerate.isEmpty()) return emptyList()

        val sb = StringBuilder()
        sb.appendLine("// Generated by :audio-wire-codec-ksp — do not edit. See docs/tasks/worklet-codec-ksp.md.")
        sb.appendLine("@file:Suppress(\"unused\", \"UNUSED_PARAMETER\", \"RemoveRedundantQualifierName\", \"USELESS_CAST\")")
        sb.appendLine()
        sb.appendLine("package $GEN_PKG")
        sb.appendLine()

        // Auto-derived structural hash of the whole wire schema. Changes iff a type/field/subtype changes, so a
        // stale-cached worklet (different build) is detected at the envelope. Never hand-bumped. See the task doc.
        val schemaSig = toGenerate.sortedBy { codecId(it) }.joinToString(";") { typeSignature(it) }
        sb.appendLine("/** Structural hash of the wire schema — frontend & worklet must agree (else a stale-build skew). */")
        sb.appendLine("const val WIRE_SCHEMA_HASH: Int = ${schemaSig.hashCode()}")
        sb.appendLine()

        for (decl in toGenerate) {
            if (Modifier.SEALED in decl.modifiers) emitSealed(decl, sb) else emitClass(decl, sb)
        }

        val files = toGenerate.mapNotNull { it.containingFile }.distinct().toTypedArray()
        codeGenerator.createNewFile(Dependencies(aggregating = true, *files), GEN_PKG, "WireCodecGenerated")
            .use { it.write(sb.toString().toByteArray()) }

        logger.warn(
            "[wire-codec] generated codec for ${toGenerate.size} types: " +
                    toGenerate.joinToString { it.simpleName.asString() })

        return emptyList()
    }

    // --- transitive collection -----------------------------------------------------------------------------

    /**
     * Walks [type]'s graph, adding codec-needing classes to [acc]. Returns true if fully supported. On any
     * unsupported shape, records a precise diagnostic (with [ctx]) into [errors] and returns false — but keeps
     * walking siblings so ONE build reports ALL problems. [ctx] is a human path like "VoiceData.adsr".
     */
    private fun collectType(type: KSType, acc: MutableSet<KSClassDeclaration>, ctx: String): Boolean {
        val decl = type.declaration
        val qn = decl.qualifiedName?.asString()

        if (isPassthrough(qn)) return true
        if (qn == LIST) return collectType(type.arguments[0].type!!.resolve(), acc, "$ctx[]")
        if (qn == MAP) {
            val k = type.arguments[0].type!!.resolve().declaration.qualifiedName?.asString()
            val v = type.arguments[1].type!!.resolve().declaration.qualifiedName?.asString()
            if (k == "kotlin.String" && v == "kotlin.Double") return true
            errors += "unsupported Map<$k, $v> at $ctx — only Map<String, Double> is supported"
            return false
        }
        if (qn != null && qn.startsWith("kotlin.")) {
            errors += "unsupported type '$qn' at $ctx (e.g. typed arrays other than DoubleArray, Pair, …)"
            return false
        }
        if (decl !is KSClassDeclaration) {
            errors += "unsupported declaration '${qn ?: decl.simpleName.asString()}' at $ctx"
            return false
        }
        if (decl.classKind == ClassKind.ENUM_CLASS) return true        // inlined as ordinal — no codec function
        if (decl.classKind == ClassKind.OBJECT) {
            errors += "unsupported object type '$qn' at $ctx — objects are only handled as sealed subtypes"
            return false
        }
        if (decl.classKind != ClassKind.CLASS && decl.classKind != ClassKind.INTERFACE) {
            errors += "unsupported declaration kind ${decl.classKind} for '$qn' at $ctx"
            return false
        }

        if (decl in acc) return true                                   // already collected / cycle

        if (Modifier.SEALED in decl.modifiers) {
            acc.add(decl)
            val subs = decl.getSealedSubclasses().toList()
            if (subs.isEmpty()) {
                errors += "sealed type '$qn' has no subclasses at $ctx"
                return false
            }
            var ok = true
            for (s in subs) {
                val sub = s.simpleName.asString()
                when {
                    // `data object` subtypes carry no fields — handled inline by the type-tag, no codec function.
                    s.classKind == ClassKind.OBJECT -> {}
                    // Intermediate sealed subtype (e.g. Cmd.Sample) — recurse; the parent flattens past it.
                    Modifier.SEALED in s.modifiers ->
                        ok = collectType(s.asStarProjectedType(), acc, "$sub (subtype of ${decl.simpleName.asString()})") && ok

                    else -> {
                        val ctor = s.primaryConstructor
                        if (ctor == null) {
                            errors += "sealed subtype '${fqn(s)}' has no primary constructor at $ctx"
                            ok = false
                        } else {
                            acc.add(s)
                            for (p in ctor.parameters) {
                                ok = collectType(p.type.resolve(), acc, "$sub.${p.name?.asString()}") && ok
                            }
                        }
                    }
                }
            }
            return ok
        }

        val ctor = decl.primaryConstructor
        if (ctor == null) {
            errors += "type '$qn' has no primary constructor at $ctx"
            return false
        }
        if (ctor.parameters.isEmpty()) {
            errors += "type '$qn' has an empty primary constructor at $ctx"
            return false
        }
        acc.add(decl)
        var ok = true
        for (p in ctor.parameters) {
            ok = collectType(p.type.resolve(), acc, "${decl.simpleName.asString()}.${p.name?.asString()}") && ok
        }
        return ok
    }

    // --- emission ------------------------------------------------------------------------------------------

    /** Types that ride a `dynamic` JS object directly: scalars + `DoubleArray` (Float64Array, cloned/transferred as-is). */
    private fun isPassthrough(qn: String?): Boolean = qn in SCALARS || qn == "kotlin.DoubleArray"

    private fun fqn(decl: KSClassDeclaration): String = decl.qualifiedName!!.asString()

    /** Flattened, collision-free codec id from the nesting chain: FilterDef.LowPass → "FilterDef_LowPass". */
    private fun codecId(decl: KSClassDeclaration): String =
        generateSequence(decl) { it.parentDeclaration as? KSClassDeclaration }
            .map { it.simpleName.asString() }
            .toList().asReversed().joinToString("_")

    private fun encName(decl: KSClassDeclaration) = "encode_${codecId(decl)}"
    private fun decName(decl: KSClassDeclaration) = "decode_${codecId(decl)}"

    /** Canonical per-type structure string, folded into [WIRE_SCHEMA_HASH]. */
    private fun typeSignature(decl: KSClassDeclaration): String =
        if (Modifier.SEALED in decl.modifiers) {
            "${codecId(decl)}|" + leafSubtypes(decl).joinToString(",") { codecId(it) }
        } else {
            "${codecId(decl)}(" + decl.primaryConstructor!!.parameters
                .joinToString(",") { "${it.name?.asString()}:${typeSig(it.type.resolve())}" } + ")"
        }

    private fun typeSig(t: KSType): String {
        val qn = t.declaration.qualifiedName?.asString() ?: "?"
        val n = if (t.isMarkedNullable) "?" else ""
        return when (qn) {
            LIST -> "List<${typeSig(t.arguments[0].type!!.resolve())}>$n"
            MAP -> "Map<${typeSig(t.arguments[0].type!!.resolve())},${typeSig(t.arguments[1].type!!.resolve())}>$n"
            else -> "$qn$n"
        }
    }

    private fun emitClass(decl: KSClassDeclaration, sb: StringBuilder) {
        val params = decl.primaryConstructor!!.parameters
        val qn = fqn(decl)

        sb.appendLine("fun ${encName(decl)}(v: $qn): dynamic {")
        sb.appendLine("    val o: dynamic = wireObj()")
        for (p in params) {
            val n = p.name!!.asString()
            sb.appendLine("    o.$n = ${encExpr("v.$n", p.type.resolve())}")
        }
        sb.appendLine("    return o")
        sb.appendLine("}")
        sb.appendLine()

        sb.appendLine("fun ${decName(decl)}(o: dynamic): $qn = $qn(")
        for (p in params) {
            val n = p.name!!.asString()
            sb.appendLine("    $n = ${decExpr("o.$n", p.type.resolve())},")
        }
        sb.appendLine(")")
        sb.appendLine()
    }

    /** Flattens a sealed hierarchy to its concrete leaves (expanding intermediate sealed types like Cmd.Sample). */
    private fun leafSubtypes(sealed: KSClassDeclaration): List<KSClassDeclaration> =
        sealed.getSealedSubclasses().toList().flatMap { s ->
            if (Modifier.SEALED in s.modifiers) leafSubtypes(s) else listOf(s)
        }

    private fun emitSealed(decl: KSClassDeclaration, sb: StringBuilder) {
        val qn = fqn(decl)
        val subs = leafSubtypes(decl)

        sb.appendLine("fun ${encName(decl)}(v: $qn): dynamic = when (v) {")
        subs.forEachIndexed { i, s ->
            // `data object` subtypes have no fields → just the tag; otherwise delegate to the subtype encoder.
            if (s.classKind == ClassKind.OBJECT) {
                sb.appendLine("    is ${fqn(s)} -> { val o = wireObj(); o.t = $i; o }")
            } else {
                sb.appendLine("    is ${fqn(s)} -> { val o = ${encName(s)}(v); o.t = $i; o }")
            }
        }
        sb.appendLine("}")
        sb.appendLine()

        sb.appendLine("fun ${decName(decl)}(o: dynamic): $qn = when (o.t.unsafeCast<Int>()) {")
        subs.forEachIndexed { i, s ->
            if (s.classKind == ClassKind.OBJECT) {
                sb.appendLine("    $i -> ${fqn(s)}")
            } else {
                sb.appendLine("    $i -> ${decName(s)}(o)")
            }
        }
        sb.appendLine("    else -> throw IllegalStateException(\"wire-codec: unknown ${codecId(decl)} tag \" + o.t)")
        sb.appendLine("}")
        sb.appendLine()
    }

    // --- per-field expressions -----------------------------------------------------------------------------

    /** Encode expression for Kotlin value [acc] (typed, so Kotlin `?.let` is safe here). */
    private fun encExpr(acc: String, type: KSType): String {
        val decl = type.declaration as? KSClassDeclaration
        val qn = decl?.qualifiedName?.asString() ?: type.declaration.qualifiedName?.asString()
        val nullable = type.isMarkedNullable

        return when {
            isPassthrough(qn) -> acc
            decl != null && decl.classKind == ClassKind.ENUM_CLASS -> if (nullable) "$acc?.ordinal" else "$acc.ordinal"
            qn == LIST -> {
                val elem = type.arguments[0].type!!.resolve()
                val v = fresh()
                val core = "wireEncodeList(SELF) { $v -> ${encExpr(v, elem)} }"
                wrapEncNullable(acc, nullable, core)
            }

            qn == MAP -> wrapEncNullable(acc, nullable, "wireEncodeStringDoubleMap(SELF)")
            decl != null -> wrapEncNullable(acc, nullable, "${encName(decl)}(SELF)")
            else -> acc
        }
    }

    /** `SELF` is the placeholder for the (non-null) value inside the wrapper. */
    private fun wrapEncNullable(acc: String, nullable: Boolean, coreWithSelf: String): String =
        if (!nullable) {
            coreWithSelf.replace("SELF", acc)
        } else {
            val v = fresh()
            "$acc?.let { $v -> ${coreWithSelf.replace("SELF", v)} }"
        }

    /** Decode expression for [acc] which is a `dynamic` (so use `if (acc != null)`, NOT `?.let`). */
    private fun decExpr(acc: String, type: KSType): String {
        val decl = type.declaration as? KSClassDeclaration
        val qn = decl?.qualifiedName?.asString() ?: type.declaration.qualifiedName?.asString()
        val nullable = type.isMarkedNullable

        return when {
            isPassthrough(qn) -> acc
            decl != null && decl.classKind == ClassKind.ENUM_CLASS ->
                wrapDecNullable(acc, nullable) { "${fqn(decl)}.entries[($it).unsafeCast<Int>()]" }

            qn == LIST -> {
                val elem = type.arguments[0].type!!.resolve()
                wrapDecNullable(acc, nullable) {
                    val e = fresh()
                    "wireDecodeList($it) { $e -> ${decExpr(e, elem)} }"
                }
            }

            qn == MAP -> wrapDecNullable(acc, nullable) { "wireDecodeStringDoubleMap($it)" }
            decl != null -> wrapDecNullable(acc, nullable) { "${decName(decl)}($it)" }
            else -> acc
        }
    }

    private inline fun wrapDecNullable(acc: String, nullable: Boolean, core: (String) -> String): String =
        if (!nullable) core(acc) else "if ($acc != null) ${core(acc)} else null"
}
