@file:Suppress("PropertyName")

import Deps.Test.configureJvmTests

// KlangScript standard library: the script-facing surface (Osc, Master, Pipeline, Math, Object,
// console, value-type extensions) and the DSL builders. Both doors of every DSL live here: the
// Kotlin API and its @KlangScript registration, generated by :klangscript-ksp like in :sprudel.
// The language itself (:klangscript) knows nothing about this module.
plugins {
    idea
    kotlin("multiplatform")
    id("com.google.devtools.ksp")
    id("io.kotest")
}

val GROUP: String by project
val VERSION_NAME: String by project

group = GROUP
version = VERSION_NAME

kotlin {
    js {
        browser {
            commonWebpackConfig {
                devtool = "source-map"
            }
        }
        compilations.all {
            compileTaskProvider.configure {
                compilerOptions.freeCompilerArgs.addAll(
                    "-Xir-property-lazy-initialization=false",
                    "-Xir-minimized-member-names=false",
                )
            }
        }
    }

    jvmToolchain(Deps.jvmTargetVersion)

    jvm {
    }

    sourceSets {
        commonMain {
            dependencies {
                api(project(":common"))
                api(project(":klangscript-annotations"))
                api(project(":klangscript"))
                api(project(":audio_bridge"))
            }
        }

        commonTest {
            dependencies {
                Deps.Test {
                    commonTestDeps()
                }
            }
        }

        jsTest {
            dependencies {
                Deps.Test {
                    jsTestDeps()
                }
            }
        }

        jvmTest {
            dependencies {
                Deps.Test {
                    jvmTestDeps()
                }
            }
        }
    }
}

tasks {
    configureJvmTests()
}

kotlin.sourceSets.commonMain {
    kotlin.srcDir("build/generated/ksp/metadata/commonMain/kotlin")
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask<*>>().configureEach {
    if (name != "kspCommonMainKotlinMetadata") {
        dependsOn("kspCommonMainKotlinMetadata")
    }
}

dependencies {
    kspCommonMainMetadata(project(":klangscript-ksp"))
}
