package io.peekandpoke.klang.pages.docs.tutorials

val allTutorials: List<Tutorial> = listOf(
    yourFirstBeatTutorial,
    yourFirstMelodyTutorial,
    shapeYourSoundTutorial,
    patternsInMotionTutorial,
    chordsAndHarmonyTutorial,
    soundDesignPlaygroundTutorial,
    remixYourselfTutorial,
    buildASongTutorial,
    moodPaintingTutorial,
    ambientOrbitsTutorial,
    polyrhythmicKitchenTutorial,
    leftRightCenterTutorial,
    rhythmicDelaysTutorial,
    waveformExplorerTutorial,
    miniNotationMasteryTutorial,
    yourFirstTrackTutorial,
    loFiBeatsTutorial,
    spacesAndRestsTutorial,
    groupAndAlternateTutorial,
    nestedPatternsTutorial,
    livePerformanceTutorial,
    transposeItTutorial,
    firstChordsTutorial,
    chordsAndMelodyTutorial,
    everyTrickTutorial,
    technoInFourLinesTutorial,
    arrangingATrackTutorial,
    pickAndChooseTutorial,
)
