package io.peekandpoke.klang.strudel.lang.docs

import io.peekandpoke.klang.script.docs.DslDocsRegistry
import io.peekandpoke.klang.script.docs.FunctionDoc

/**
 * Platform-specific generated documentation from @StrudelDsl annotated functions.
 * Actual implementations are generated by KSP in platform-specific source sets.
 */
@Suppress("KotlinNoActualForExpect", "RedundantSuppression")
expect val generatedStrudelFunctionDocs: Map<String, FunctionDoc>

/**
 * Registers all Strudel DSL function documentation with the KlangScript documentation registry.
 *
 * This should be called during initialization to make Strudel documentation available
 * for IDE completion, CodeMirror autocomplete, and documentation pages.
 *
 * @param registry The registry to register docs into (defaults to global registry)
 */
fun registerStrudelDocs(registry: DslDocsRegistry = DslDocsRegistry.global) {
    // Register auto-generated docs (all @StrudelDsl functions)
    registry.registerAll(generatedStrudelFunctionDocs)
}
