package io.peekandpoke.klang.strudel.ksp

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.validate

/**
 * KSP processor that generates documentation entries from @StrudelDsl annotated functions.
 *
 * This processor:
 * 1. Finds all functions annotated with @StrudelDsl
 * 2. Extracts KDoc documentation from those functions
 * 3. Generates FunctionDoc entries automatically
 */
class StrudelDocsProcessor(
    environment: SymbolProcessorEnvironment,
) : SymbolProcessor {

    private val codeGenerator: CodeGenerator = environment.codeGenerator
    private val logger: KSPLogger = environment.logger

    override fun process(resolver: Resolver): List<KSAnnotated> {
        logger.info("StrudelDocsProcessor: Starting documentation generation")

        // Find all functions annotated with @StrudelDsl
        val strudelDslFunctions = resolver
            .getSymbolsWithAnnotation("io.peekandpoke.klang.strudel.lang.StrudelDsl")
            .filterIsInstance<KSFunctionDeclaration>()
            .toList()

        logger.info("StrudelDocsProcessor: Found ${strudelDslFunctions.size} @StrudelDsl functions")

        if (strudelDslFunctions.isEmpty()) {
            return emptyList()
        }

        // Generate documentation file
        generateDocsFile(strudelDslFunctions)

        // Return symbols that couldn't be processed (for incremental processing)
        return strudelDslFunctions.filterNot { it.validate() }
    }

    private fun generateDocsFile(functions: List<KSFunctionDeclaration>) {
        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = true),
            packageName = "io.peekandpoke.klang.strudel.lang.docs",
            fileName = "GeneratedStrudelDocs",
            extensionName = "kt"
        )

        file.bufferedWriter().use { writer ->
            writer.write(generateDocsCode(functions))
        }

        logger.info("StrudelDocsProcessor: Generated documentation file")
    }

    private fun generateDocsCode(functions: List<KSFunctionDeclaration>): String {
        return buildString {
            appendLine("// Generated by StrudelDocsProcessor - DO NOT EDIT")
            appendLine()
            appendLine("package io.peekandpoke.klang.strudel.lang.docs")
            appendLine()
            appendLine("import io.peekandpoke.klang.script.docs.*")
            appendLine()
            appendLine("/**")
            appendLine(" * Auto-generated Strudel DSL function documentation.")
            appendLine(" * Generated from @StrudelDsl annotated functions.")
            appendLine(" * Platform-specific actual implementation of the expected declaration.")
            appendLine(" */")
            appendLine("actual val generatedStrudelFunctionDocs = mapOf(")

            functions.forEachIndexed { index, function ->
                append(generateFunctionDocEntry(function))
                if (index < functions.size - 1) {
                    appendLine(",")
                }
            }

            appendLine()
            appendLine(")")
        }
    }

    private fun generateFunctionDocEntry(function: KSFunctionDeclaration): String {
        val functionName = function.simpleName.asString()
        val kdoc = function.docString

        logger.info("StrudelDocsProcessor: Processing function '$functionName'")
        if (kdoc != null) {
            logger.info("StrudelDocsProcessor: KDoc found for '$functionName': ${kdoc.take(100)}...")
        } else {
            logger.warn("StrudelDocsProcessor: No KDoc found for '$functionName'")
        }

        return buildString {
            appendLine()
            appendLine("    \"$functionName\" to FunctionDoc(")
            appendLine("        name = \"$functionName\",")
            appendLine("        category = \"TODO\", // TODO: Extract from KDoc or annotation")
            appendLine("        tags = emptyList(), // TODO: Extract from KDoc")
            appendLine("        library = \"strudel\",")
            appendLine("        variants = listOf(")
            appendLine("            // TODO: Generate VariantDoc from function signature")
            appendLine("        )")
            append("    )")
        }
    }
}
